name: workflow-a

on:
  push:
  schedule:
    - cron: '* * * * *'

jobs:
  workflow-a-job-a:
    strategy:
      matrix:
        stage: ['DEV']
      fail-fast: true
      max-parallel: 2
    environment:
      name: '${{ matrix.stage }}'
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5; true
